web: NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program poetry run gunicorn app.main:app --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:${PORT}
release: scripts/heroku_release.sh
